jobs:
  include:
    # - stage: test
    # language: node_js
    # node_js:
    # - 6.2.1
    # - stage: deploy
    # script: skip
    # deploy:
    # provider: heroku
    # api_key:
    # secure: UIQWuiie0kaNNWYBnPxJLGVzdWxbcC0R1yyh6cDFbOc9vKb9X6wum/UjE/uGjo73LbJgHqpsnXaiskDzgi3gMrjkiGiylk9bNJg9QWBx8U7SroeTL6yrXqi1786C3ge1aMmSjrccQ+vV+K12auc+iTDoZiIdeKWi9ysiIf1uXvyTlP5FfAo+YIiZqeaVgOZpG0AAiM8gefhfSv4nmfbz8/07c8yFIPGON89tYYHHV8gPxTGIafe0JZXaI00BsxyWgbm0+WoTyng6un/jwkTPmQ2Ah0Kw4xx+XchJPFDX45wvsO7KCmz+G5BGfM49owCEccUh3HBlMdXuDRnlWmkH6FQfKDTYWgIUqEOj5O3XL3X3OIHO3TlMQsGqAwFLIs2boXmKB3dYLMZeo3e2YuA/hljFaNsJvoenCow65Cf+dsJLjbh6MSswAvp9W6elUFucOUKK3uRI87Fh0OBtpiIUiW5X/lsj8Ct2w5VVFfecyE8wqPQilqlzNH32yNmgsixyBcpLXYt3lzATPMR1lg6QZFCXe3+vRYgoI3KHV8xi3IJRE1gUIg6nvl4c7BAqDschYIYGuwbOBBx+6StuGoympfSOgPbt+Uy9HJ/TkR3G5fWgvVdPumCT7Les8dcMewEXcvLEkYDiBzfolg6RMdin6vRYuJpBeZBq0N9y5w67Mh8=
    # app: doer-web-staging
  - stage: e2etest
    before_install:
      - git clone https://github.com/ctailor2/doerE2ETests.git
      - cd doerE2ETests
    install:
      - npm install
    script:
      - ./node_modules/.bin/cypress run

