export const SIGNUP_REQUEST_ACTION = 'SIGNUP_REQUEST_ACTION';
export const LOGIN_REQUEST_ACTION = 'LOGIN_REQUEST_ACTION';
export const LOGOUT_REQUEST_ACTION = 'LOGOUT_REQUEST_ACTION';
export const STORE_SESSION_ACTION = 'STORE_SESSION_ACTION';
export const GET_TODOS_REQUEST_ACTION = 'GET_TODOS_REQUEST_ACTION';
export const STORE_TODOS_ACTION = 'STORE_TODOS_ACTION';
export const CREATE_TODO_REQUEST_ACTION = 'CREATE_TODO_REQUEST_ACTION';