export const SIGNUP_REQUEST_ACTION = 'SIGNUP_REQUEST_ACTION';
export const LOGIN_REQUEST_ACTION = 'LOGIN_REQUEST_ACTION';
export const LOGOUT_REQUEST_ACTION = 'LOGOUT_REQUEST_ACTION';
export const STORE_SESSION_ACTION = 'STORE_SESSION_ACTION';

export const CREATE_TODO_REQUEST_ACTION = 'CREATE_TODO_REQUEST_ACTION';
export const DELETE_TODO_REQUEST_ACTION = 'DELETE_TODO_REQUEST_ACTION';
export const DISPLACE_TODO_REQUEST_ACTION = 'DISPLACE_TODO_REQUEST_ACTION';
export const UPDATE_TODO_REQUEST_ACTION = 'UPDATE_TODO_REQUEST_ACTION';
export const COMPLETE_TODO_REQUEST_ACTION = 'COMPLETE_TODO_REQUEST_ACTION';
export const MOVE_TODO_REQUEST_ACTION = 'MOVE_TODO_REQUEST_ACTION';
export const PULL_TODOS_REQUEST_ACTION = 'PULL_TODOS_REQUEST_ACTION';
export const ESCALATE_TODOS_REQUEST_ACTION = 'ESCALATE_TODOS_REQUEST_ACTION';

export const STORE_LINKS_ACTION = 'STORE_LINKS_ACTION';
export const PERSIST_LINK_ACTION = 'PERSIST_LINK_ACTION';

export const GET_BASE_RESOURCES_REQUEST_ACTION = 'GET_BASE_RESOURCES_REQUEST_ACTION';
export const GET_ROOT_RESOURCES_REQUEST_ACTION = 'GET_ROOT_RESOURCES_REQUEST_ACTION';
export const GET_TODO_RESOURCES_REQUEST_ACTION = 'GET_TODO_RESOURCES_REQUEST_ACTION';
export const GET_HISTORY_RESOURCES_REQUEST_ACTION = 'GET_HISTORY_RESOURCES_REQUEST_ACTION';

export const LOAD_TODOS_VIEW_ACTION = 'LOAD_TODOS_VIEW_ACTION';
export const LOAD_HISTORY_VIEW_ACTION = 'LOAD_HISTORY_VIEW_ACTION';

export const GET_LIST_REQUEST_ACTION = 'GET_LIST_REQUEST_ACTION';
export const STORE_LIST_ACTION = 'STORE_LIST_ACTION';
export const UNLOCK_LIST_REQUEST_ACTION = 'UNLOCK_LIST_REQUEST_ACTION';

export const GET_COMPLETED_LIST_REQUEST_ACTION = 'GET_COMPLETED_LIST_REQUEST_ACTION';
export const STORE_COMPLETED_LIST_ACTION = 'STORE_COMPLETED_LIST_ACTION';

export const STORE_ERRORS_ACTION = 'STORE_ERRORS_ACTION';
export const DISMISS_GLOBAL_ALERT_ACTION = 'DISMISS_GLOBAL_ALERT_ACTION';
export const CLEAR_ERRORS_ACTION = 'CLEAR_ERRORS_ACTION';